[build]
  command = "npm run build"
  publish = "build/client"


[dev]
  command = "npm run dev"
  port = 5173

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, s-maxage=31536000, immutable"
